jekip/naive-ui-admin

- src/components/Lockscreen/Lockscreen.vue
> 添加锁屏时enter键解除锁屏

- src/layout/components/TagsView/index.vue
> feat: TagsView自动滚动功能

- .env.development
- src/layout/index.vue
- src/settings/projectSetting.ts
- types/config.d.ts
> 更新侧边导航栏移动端显示为modal显示。

- src/components/Table/src/hooks/useDataSource.ts
添加 table-hook( useDataSource ) 中 beforeRequest 和 afterRequest 回调
> feat(function): add table-fetch(before and after interceptor)

- src/hooks/web/useECharts.ts
> 修复 useECharts Hooks 报错和暗色模式 bug

- src/components/Table/src/hooks/useDataSource.ts
- src/components/Table/src/props.ts
- src/utils/is/index.ts
fix(function):修复 useDataSource 中请求前请求后回调未在prop中声明、isFunction支持普通、箭头函数判断
> fix(function):修复 useDataSource 中请求前请求后回调未在prop中声明、isFunction支持普通、箭头函数判断

- src/components/Table/src/Table.vue
- src/components/Table/src/components/TableAction.vue
- src/components/Table/src/props.ts
- src/components/Table/src/types/tableAction.ts
- src/views/comp/table/basic.vue
> BaseTableAction 新增 icon 配置项 + 表格斑马纹

- src/config/website.config.ts
- src/layout/components/Header/index.vue
- src/layout/components/Logo/index.vue
- src/views/login/index.vue
修改配置文件就可以快速修改项目的logo与项目名称还有login页的简单文字修改。
> ✨ feat: 添加网站配置文件

- src/layout/components/Menu/index.vue
issues链接：https://github.com/jekip/naive-ui-admin/issues/151
将设置selectedKeys抽调出单独函数 在updateMenu函数后调用。
可测试解决该问题
>  fix: 路由配置activeMenu的bug 

- src/components/Upload/src/BasicUpload.vue
上传组件里默认图片没显示，图片路径错误加载不出来的时候删除按钮不显示
> fix(BasicUpload): 修复默认图片不显示bug,默认图片加载错误时删除按钮不显示bug

- src/views/form/basicForm/index.vue
> docs: 文案修改

- src/utils/lib/echarts.ts
echarts.ts中引入GraphicComponent，否则graphic不生效
> feat: add GraphicComponent

- src/router/modules/docs.ts
- src/router/modules/frame.ts
- src/views/about/index.vue
> fix: 替换项目文档地址

- src/components/Form/src/types/form.ts
FormActionType中setFieldsValue类型报错修复
> feat: 类型修改

- src/utils/index.ts
- yarn.lock
增加了菜单font图标的适配
1. font 图标(Font class)
2.font 图标(Unicode)
3.font svg 图标
> feat:add 增加了菜单font图标的适配

- src/store/modules/user.ts
出现了localstorage里面，关于用户信息的expire都到2042年了
> fix:两杯都*1000，导致最终过期时间为7000天

- src/layout/components/Header/index.vue
fix this issue: [#216](https://github.com/jekip/naive-ui-admin/issues/216)
> fix: reload page warning

- mock/_createProductionServer.ts
- pnpm-lock.yaml
- src/router/index.ts
- src/router/types.ts
解决importMetaGlob引入文件后，类型为unknown的问题
> fix: add type for importMetaGlob

- src/views/system/role/role.vue
> fix: formRef is not used and undefined

- src/views/setting/account/SafetySetting.vue
> fix: adjust margins to prevent text from being cut off

- src/components/Upload/src/BasicUpload.vue
将基础表单的图片上传的图标和文字居中了，强迫症实在不能忍 (｀・ω・´)
> style(BasicUpload): center upload icon and text in BasicForm

- src/components/Form/src/BasicForm.vue
- Allow push Enter key to query the table form.
> See button api: [attr-type](https://www.naiveui.com/zh-CN/os-theme/components/button#API)
> feat(BasicForm): trigger query via Enter key

- src/views/setting/account/account.vue
- src/views/setting/system/system.vue
修复 `src/views/setting/system/system.vue` 中 `type`、`typeTitle `两个变量因封装忘记修改`template`中的数据导致页面显示有误的bug
> 修复封装state时忘记修改html导致的报错

- src/hooks/setting/index.ts
- types/config.d.ts
VITE_USE_MOCK and VITE_LOGGER_MOCK is string while get value from import.meta.env
> 🐞 fix(env): fix env type
